services:
  # Main StayFinder Application (Frontend + Backend)
  - type: web
    name: stayfinder-app
    env: node
    plan: free
    buildCommand: npm install && CI=false npm run build
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: CI
        value: false 