services:
  # Main StayFinder Application (Frontend + Backend)
  - type: web
    name: stayfinder-app
    env: node
    plan: free
    buildCommand: |
      npm run install-all
      npm run build:prod
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5000
    healthCheckPath: /health
    autoDeploy: true 