services:
  # Main StayFinder Application (Frontend + Backend)
  - type: web
    name: stayfinder-app
    env: node
    plan: free
    buildCommand: |
      npm install
      cd server && npm install
      cd ..
      CI=false npm run build
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        fromService:
          type: web
          name: stayfinder-app
          envVarKey: PORT
    healthCheckPath: /health
    autoDeploy: true 